name: Issue Handler

on:
  issues:
    types: [opened, edited, closed]

jobs:
  handle-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue event info
        run: |
          echo "Issue event: ${{ github.event.action }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
